# When upgrading passenger-ruby image version, make sure to update passenger version in Gemfile
FROM phusion/passenger-ruby27:2.5.0

LABEL org.opencontainers.image.source=https://github.com/gwu-libraries/scholarspace-hyrax

RUN apt update && apt install -y libpq-dev unzip clamav-daemon curl libreoffice libcurl4-openssl-dev ffmpeg gnupg2 libxml2 libxml2-dev wget

RUN apt update && apt build-dep -y imagemagick

RUN apt install -y checkinstall libwebp-dev libopenjp2-7-dev librsvg2-dev libde265-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN cd /opt \
    && wget https://www.imagemagick.org/archive/releases/ImageMagick-7.1.1-13.tar.xz \
    && tar xf ImageMagick-7.1.1-13.tar.xz \
    && cd ImageMagick-7.1.1-13 \
    && ./configure --enable-shared --with-modules --with-gslib \
    && make \
    && make install \
    && ldconfig /usr/local/lib \
    && identify -version \
    && rm /opt/ImageMagick-7.1.1-13.tar.xz

# FITS install
WORKDIR /usr/local/bin

RUN wget https://github.com/harvard-lts/fits/releases/download/1.5.0/fits-1.5.0.zip \
    && unzip fits-1.5.0.zip -d fits-1.5.0 \
    && rm fits-1.5.0.zip \
    && chmod a+x fits-1.5.0/fits*.sh
    
# Uninstall Ruby version from image and install our version
# bash -lc is necessary per the configuration of the base image 
RUN bash -lc "rvm remove ruby-2.7.7 && rvm install ruby-2.7.3"