Master's Thesis:
  - M.A.
  - M.S.
  - M.P.H.
  - LL.M.
  - M.F.A.
  - M.A.T.
  - M.P.S.
  - M.B.A.
  - M.F.S.
  - M.Int.St.
  - M.P.H.
  - M.P.P.
Dissertation:
  - Ph.D.
  - Ed.D.
  - D.Engr.
  - Dr.P.H.
  - D.Sc.
  - S.J.D.
