static:
  citation_institution: George Washington University
attributes:
  citation_title: title
  citation_author: creator
  citation_type: resource_type
  dc.type: resource_type
  citation_publication_date: date_created
  dc.issued: date_created
  citation_keywords: keyword
  citation_pdf_url: download_url
