static:
  citation_institution: George Washington University
attributes:
  citation_title: title
  citation_author: creator
  citation_type: resource_type
  dc.type: resource_type
  citation_date: publication_date
  citation_keywords: keyword
  citation_pdf_url: download_url
