# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
#  include ::Hyrax::FileSetBehavior

  property :bulkrax_identifier, predicate: ::RDF::URI("https://iro.bl.uk/resource#bulkraxIdentifier"), multiple: false do |index|
    index.as :stored_searchable, :facetable
  end

  include ::Hyrax::FileSetBehavior
end
